config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :tweets
    post 'follow/:follower_id' => 'follow_relation#create', as: :follow
    delete 'follow/:follower_id' => 'follow_relation#destroy', as: :unfollow
  end

  root 'users#index'

end

app/models/follow_relation.rb
class FollowRelation < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :tweets

  validates :tweet_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :hashtags

  validates :content, presence: true
  validates :content, length: { in: 1..140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  has_many :active_relationships, class_name: "FollowRelation", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "FollowRelation", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(followed)
    active_relationships.create(followed_id: followed.id)
  end

  def unfollow(followed)
    active_relationships.where(followed_id: followed.id).first.destroy
  end

  def follow?(user)
    following.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follow_relation_controller.rb
class FollowRelationController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    user = User.find_by(id: params[:user_id])
    to_follow = User.find_by(id: params[:follower_id])

    respond_to do |format|
      if user.follow(to_follow)
        format.html { redirect_to user_tweets_path(user_id: params[:user_id]), notice: 'User successfully followed.' }
      else
        format.html { redirect_to user_tweets_path(user_id: params[:user_id]), notice: 'Error while creating relation' }
      end
    end
  end

  def destroy
    user = User.find_by(id: params[:user_id])
    to_unfollow = User.find_by(id: params[:follower_id])

    respond_to do |format|
      if user.unfollow(to_unfollow)
        format.html { redirect_to user_tweets_path(user_id: params[:user_id]), notice: 'User successfully unfollow.' }
      else
        format.html { redirect_to user_tweets_path(user_id: params[:user_id]), notice: 'Error while creating relation' }
      end
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :find_user

  def index
    @users = User.all
    # @tweets = @user.tweets.order 'tweets.created_at DESC'

    ids = @user.following.pluck(:id)
    ids << @user.id
    @tweets = Tweet.where(user_id: ids).order 'tweets.created_at DESC'

    # OLD -- sort not work ?
    # @hashtags = Hashtag.group(:hashtag).limit(10).count
    # @hashtags.sort_by {|e| -e[1]}
    # New with sort in sql
    sql = "SELECT hashtag, count(hashtag) FROM hashtags GROUP BY hashtag ORDER BY 2 DESC"
    @hashtags = ActiveRecord::Base.connection.execute(sql)
  end

  def show

  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = @user.tweets.create(tweet_params)

    respond_to do |format|
      if @user.save
        process_hashtags(tweet)

        format.html { redirect_to user_tweets_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end

    def find_user
      @user = User.find_by_id(params[:user_id])
    end

    def process_hashtags(tweet)
      tweet.content.scan(/\B#\w*[a-zA-Z]+\w*/).each do |tag|
        h = Hashtag.create({hashtag: tag, tweet_id: tweet.id })
        h.save
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :firstname, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follow_relation_helper.rb
module FollowRelationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follow_relation/create.html.erb
<h1>FollowRelation#create</h1>
<p>Find me in app/views/follow_relation/create.html.erb</p>

app/views/follow_relation/destroy.html.erb
<h1>FollowRelation#destroy</h1>
<p>Find me in app/views/follow_relation/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for [@user, @tweet] do |t| %>


  <%= t.hidden_field :user_id, value: @user.id %>
  <div class="input-field">
    <%= t.label :content %><br>
    <%= t.text_field :content %>
  </div>

  <div class="btn waves-effect waves-light grey">
    <%= t.submit %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>List of tweets by user</h1>
  <div class="row">
    <div class="col s6">
      <h4><%= @user.firstname + " " + @user.name %></h4>
      <span class="right-align">Follow : <%= @user.following.length %>, Followers : <%= @user.followers.length %></span>
    </div>
    <div class="col s2">
      <%= link_to 'Tweeter', new_user_tweet_path(@user) %>
    </div>
  </div>
  <div class="row">
    <div class="col s8">
      <% @tweets.each do |tweet| %>
        <div class="col s12">
          <div class="card-panel teal">
            <div class="card-content white-text">
              <div class="card-title">
                <% if @user.img_url != '' %>
                    <img src="<%= path_to_asset("images/"+@user.img_url) %>" alt="" class="circle">
                  <% else %>
                    <img src="<%= path_to_asset("images/ninja.svg") %>" alt="" class="circle">
                <% end %>
                <h5><%= @user.name %> à dit :</h5>
              </div>
              <br>
              <span>
                <%= tweet.content %>
              </span>
            </div>
            <div class="card-action">
              <span class="right">
                <%= distance_of_time_in_words_to_now tweet.created_at %> ago
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col s4">
      <ul class="collection with-header">
        <li class="collapsible-header">Utilisateurs</li>
        <% @users.each do |user| %>
          <% if user.id != @user.id %>
            <li class="collection-item">
              <span><%= user.firstname + " " + user.name %></span>
              <span class="secondary-content">
                <% if @user.follow? user %>
                  <%= link_to user_follow_path(@user, user), remote: true, method: :delete do%>
                    <i class="material-icons">close</i>
                  <% end %>
                <% else %>
                  <%= link_to user_unfollow_path(@user, user), remote: true, method: :post do%>
                    <i class="material-icons">add</i>
                  <% end %>
                <% end %>
              </span>
            </li>
          <% end %>
        <% end %>
      </ul>

      <ul class="collection with-header">
        <li class="collapsible-header">Hashtag populaires</li>
        <% if @hashtags.length > 0 %>
          <% @hashtags.each do |hashtag| %>
            <li class="collection-item"><%= hashtag[0] %></li>
          <% end %>
        <% else %>
            <li class="collection-item">Aucun element à afficher</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tweets_path(@user) %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>List of tweets by user</h1>

<div class="row">
  <% @tweets.each do |tweet| %>
    <div class="col s8 offset-l2">
      <div class="card-panel teal">
        <span class="white-text">
          <%= tweet.content %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="input-field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="input-field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="btn waves-effect waves-light grey">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Firstname</th>
      <th>Img url</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.firstname %></td>
        <td><%= user.img_url %></td>
        <td><%= link_to 'Connect', user_tweets_path(user) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @user.img_url %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>